'''
Write the sequence model as a notebook in google colab, then download as a .py and put it here.
Make sure to use the functions found in utils.py for loading data, mapping ids, etc.
Input:

    Watch Sequences: A list of mediaId sequences for a specific user.

    Pre-computed Embeddings: The 128-dim vectors generated by the gnn_model.py.

Output:

    Prediction Vector: A probability distribution (via a Softmax layer) across all possible mediaIds in the dataset, indicating the likelihood of each being the "next" watch.
'''
