'''
Write the sequence model here.
Input:

    Watch Sequences: A list of mediaId sequences for a specific user.

    Pre-computed Embeddings: The 128-dim vectors generated by the gnn_model.py.

Output:

    Prediction Vector: A probability distribution (via a Softmax layer) across all possible mediaIds in the dataset, indicating the likelihood of each being the "next" watch.
'''
